import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { cn } from "@/lib/utils";

import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const poppins = Poppins({
	weight: ["400", "500", "600", "700"],
	display: "swap",
	subsets: ["latin"],
	variable: "--font-poppins"
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<GlobalLayoutProps>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={cn(poppins.className, "antialiased")} suppressHydrationWarning>
				{children}
				<Toaster richColors position="top-right" closeButton style={{ zIndex: 9999 }} />
			</body>
		</html>
	);
}

